const fs=require('node:fs'),path=require('node:path');
module.exports=async({run,ok,click,fill,btn,until,send,open,profile,sleep})=>{
  const has=async text=>(await run('document.body.innerText')).includes(text);
  const route=async hash=>{await run(`location.hash=${JSON.stringify(hash)}`);await sleep(150);};
  const input=async(index,part,value)=>run(`(()=>{const group=document.querySelectorAll('[data-editor-field]')[${index}];const el=group.querySelector(${JSON.stringify(part)});${typeof value==='boolean'?`el.checked=${value};el.dispatchEvent(new Event('change',{bubbles:true}));`:`el.value=${JSON.stringify(value)};el.dispatchEvent(new Event(${JSON.stringify(part==='select'?'change':'input')},{bubbles:true}));`}})()`);
  const setFile=async(file)=>{const doc=await send('DOM.getDocument'),el=await send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'#importFile'});await send('DOM.setFileInputFiles',{files:[file],nodeId:el.nodeId});await sleep(250);};
  const importText=async(name,text)=>{const file=path.join(profile,name+'.json');fs.writeFileSync(file,text);await route('#/');await setFile(file);};
  await route('#/');await click('#newBtn');await fill('#newName','rich');await click('#newKeyFind');
  await until(`document.body.innerText.includes('Recognized')`);await click('#createBox');await until(`location.hash==='#/box/rich'&&!!document.querySelector('#lockBtn')`);
  await click('#tab-items');await click('#new-record');await fill('#record-title','Recovery <img src=x onerror=alert(1)>');
  const values=[' 0001\n  second line ', 'x'.repeat(10000)+'\nend', 'https://example.org/recover', 'javascript:alert(1)', '', ...Array.from({length:15},(_,i)=>'value '+i)];
  for(let i=0;i<20;i++){
    await btn('Add field');await input(i,'input[id$="-name"]',i<2?'Duplicate':'Field '+i);
    if(i===1)await input(i,'select','multiline');
    if(i===2||i===3)await input(i,'select','url');
    if(i>0)await input(i,'input[type=checkbox]',false);
    await input(i,'textarea[data-value]',values[i]);
  }
  ok(await run(`document.querySelectorAll('[data-editor-field]').length===20&&[...document.querySelectorAll('input,textarea')].every(el=>el.hasAttribute('data-1p-ignore')&&el.hasAttribute('data-lpignore')&&el.hasAttribute('data-bwignore'))`),'twenty fields use labelled, password-manager-ignored controls');
  await click('#save-record');await until(`!document.querySelector('#record-title')`);
  const first=await run(`(async()=>{const C=await import('./crypto.js'),W=await import('./webauthn.js');const box=(await lib.get('rich')).box;const data=await W.unlockVault(box);window.__richData=data;const record=JSON.parse(await C.decryptText(data,box.items[0]));window.__richExpected=record;return record;})()`);
  ok(first.fields.length===20&&JSON.stringify(first.fields.map(f=>f.value))===JSON.stringify(values),'twenty fields and a ten-thousand-character value persist without truncation');
  ok(!await run(`document.querySelector('.record-detail').outerHTML.includes('0001')||!!document.querySelector('.record-detail img')||!!document.querySelector('a[href^="javascript:"]')`),'malicious titles remain literal and hidden values stay absent from the rendered record');
  for(const theme of ['light','dark']){
    await send('Emulation.setDeviceMetricsOverride',{width:320,height:800,deviceScaleFactor:1,mobile:true});await click(`[data-theme-choice="${theme}"]`);
    ok(await run(`document.documentElement.scrollWidth<=innerWidth&&[...document.querySelectorAll('.record-detail button')].every(el=>el.getBoundingClientRect().right<=innerWidth)`),'long record values and controls fit 320 pixels in '+theme);
  }
  await btn('Edit');
  ok(await run(`document.activeElement.id==='record-title'&&getComputedStyle(document.activeElement).outlineStyle!=='none'`),'editing focuses the title with visible keyboard focus');
  await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});
  ok(await run(`document.activeElement.id.endsWith('-name')`),'keyboard Tab reaches the first field name');
  await btn('Replace');await run(`document.querySelector('textarea[data-value]').focus()`);
  await send('Input.insertText',{text:' typed\nreplacement '});
  ok(await run(`document.querySelector('textarea[data-value]').value===' typed\\nreplacement '&&getComputedStyle(document.querySelector('textarea[data-value]')).webkitTextSecurity==='disc'`),'masked multiline replacement accepts browser text input without truncation');
  await btn('Show');await click('[data-confirm-toggle]');
  ok(await run(`document.querySelector('textarea[data-confirmation]').value===''&&getComputedStyle(document.querySelector('textarea[data-confirmation]')).webkitTextSecurity==='disc'&&getComputedStyle(document.querySelector('textarea[data-value]')).webkitTextSecurity==='none'`),'primary and optional confirmation reveal choices are independent');
  await btn('Cancel');await btn('Edit');
  await fill('#record-title','Unsaved title');await run('window.__confirmChoice=false');await click('#tab-sync');
  ok(await run(`document.querySelector('#record-title')?.value==='Unsaved title'`),'rejecting tab departure preserves the dirty draft');
  await route('#/settings');
  ok(await run(`location.hash==='#/box/rich'&&document.querySelector('#record-title')?.value==='Unsaved title'`),'rejecting hash navigation restores the route and the same draft');
  await run('window.__confirmChoice=true');await click('#lockBtn');
  ok(!await run(`!!document.querySelector('#record-title')||document.body.innerText.includes('Unsaved title')`),'Lock drops the draft immediately without a discard prompt');
  await send('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
  await click('#unlockBtn');await until(`!!document.querySelector('#new-record')`);
  await run(`window.__realTimer=window.setTimeout;window.setTimeout=(callback,delay,...args)=>{if(delay===60000){window.__clearCopied=callback;return 987654;}return window.__realTimer(callback,delay,...args);};`);
  await click('button.copy');await sleep(80);
  ok(await run('navigator.clipboard.readText()')===values[0],'hidden multiline copy sends the exact primary value to the real clipboard');
  await click('#lockBtn');await run(`window.setTimeout=window.__realTimer;window.__clearCopied()`);
  ok(await run('navigator.clipboard.readText()')==='','Lock leaves the scheduled best-effort clipboard clear active');
  await click('#unlockBtn');await until(`!!document.querySelector('#new-record')`);
  await run(`document.querySelectorAll('button.copy')[4].click()`);await sleep(80);
  ok(await run('navigator.clipboard.readText()')==='','empty values have working copy controls');
  await click('#tab-sync');
  await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:profile});await click('#dlBtn');
  for(let attempt=0;attempt<30&&!fs.existsSync(path.join(profile,'rich.json'));attempt++)await sleep(100);
  const exported=fs.readFileSync(path.join(profile,'rich.json'),'utf8');
  ok(exported===await run(`lib.get('rich').then(r=>r.sourceText)`),'Download emits the complete exact encrypted source');
  ok(!exported.includes(first.title)&&!exported.includes(values[0])&&!exported.includes('Duplicate'),'download ciphertext contains no record title, field labels or synthetic private values');
  await importText('rich-copy',exported);await route('#/box/rich-copy');await click('#tab-items');await click('#unlockBtn');await until(`!!document.querySelector('#new-record')`);
  const imported=await run(`(async()=>{const C=await import('./crypto.js'),W=await import('./webauthn.js');const box=(await lib.get('rich-copy')).box;return JSON.parse(await C.decryptText(await W.unlockVault(box),box.items[0]));})()`);
  ok(JSON.stringify(imported)===JSON.stringify(first),'download and file import retain every field attribute and exact value');
  await open('#/box/rich');await click('#unlockBtn');await until(`!!document.querySelector('#new-record')`);
  const reloaded=await run(`(async()=>{const C=await import('./crypto.js'),W=await import('./webauthn.js');const box=(await lib.get('rich')).box;return JSON.parse(await C.decryptText(await W.unlockVault(box),box.items[0]));})()`);
  ok(JSON.stringify(reloaded)===JSON.stringify(first),'reload and authenticator unlock retain all twenty ordered fields');
  // Restore a session-only GitHub connection after the real page reload.
  await route('#/settings');await fill('#tokIn','ghp_FAKE');await click('#useTok');await sleep(200);await route('#/box/rich');await click('#tab-sync');await click('#pushBtn');
  await until(`!!window.__gh.files['boxes/rich.json']`);
  ok(await run(`(async()=>window.__gh.files['boxes/rich.json']===(await lib.get('rich')).sourceText)()`),'Push transports the exact encrypted source without reserialization');
  const replacement=await run(`(async()=>{
    const C=await import('./crypto.js'),W=await import('./webauthn.js');const old=(await lib.get('rich')).box;
    window.__oldRichData=await W.unlockVault(old);const data=C.newDataKey();window.__replacementData=data;
    const record={format:'fido2box-record',version:1,type:'recovery',id:'replacement',title:'Replacement record',fields:[]};
    const key=await W.enrolKnownKey(old.keys[0],data);const box={...old,keys:[key],items:[await C.encryptText(data,JSON.stringify(record))]};
    window.__replacementSource=' '+JSON.stringify(box)+'\\n';window.__gh.files['boxes/rich.json']=window.__replacementSource;return box;
  })()`);
  await route('#/');await click('#refreshBtn');await sleep(250);await route('#/box/rich');await click('#tab-sync');await click('#pullBtn');
  await until(`!document.querySelector('#lockBtn')`);await click('#tab-items');
  ok(await has('This box is locked')&&!await has(first.title),'same-revision different-key Pull clears old plaintext and requires unlock');
  await click('#unlockBtn');await until(`document.body.innerText.includes('Replacement record')`);await btn('Edit');await fill('#record-title','Replacement saved');await click('#save-record');await until(`!document.querySelector('#record-title')`);
  ok(await run(`(async()=>{const C=await import('./crypto.js'),box=(await lib.get('rich')).box;let oldRefused=false;try{await C.decryptText(window.__oldRichData,box.items[0]);}catch{oldRefused=true;}return oldRefused&&JSON.parse(await C.decryptText(window.__replacementData,box.items[0])).title==='Replacement saved';})()`),'a save after Pull uses only the replacement data key and remains decryptable');
  const beforeDelayedPull=await run(`lib.get('rich').then(r=>r.sourceText)`);
  await run(`(async()=>{const box=(await lib.get('rich')).box;window.__gh.files['boxes/rich.json']=JSON.stringify({...box,rev:box.rev+10});window.__fetchBeforeDelay=window.fetch;window.__pendingPull=false;window.fetch=async(...args)=>{const response=await window.__fetchBeforeDelay(...args);if(String(args[0]).endsWith('/contents/boxes/rich.json')){window.__pendingPull=true;await new Promise(resolve=>{window.__releasePull=resolve;});}return response;};})()`);
  await click('#tab-sync');await click('#pullBtn');await until(`window.__pendingPull`);
  ok(await run(`!document.querySelector('#lockBtn')`),'starting a deferred Pull invalidates the old session before network completion');
  await click('#tab-items');await click('#unlockBtn');await until(`!!document.querySelector('#new-record')`);
  await run(`window.fetch=window.__fetchBeforeDelay;window.__releasePull();`);await sleep(150);
  ok(await run(`lib.get('rich').then(r=>r.sourceText)`)===beforeDelayedPull&&await has('Replacement saved'),'a Pull response arriving after a fresh unlock cannot overwrite its new session');
  // Full v1 note migration, with the actual UI and a credential already held by the virtual key.
  const legacy=await run(`(async()=>{const C=await import('./crypto.js'),W=await import('./webauthn.js');const box=(await lib.get('rich')).box,data=await W.unlockVault(box),sealed=await C.encryptText(data,'prefix\\r\\nSecret Key: 0001\\rtrailing  ');return ' { '+JSON.stringify({v:1,entries:box.keys,rpId:'localhost',...sealed}).slice(1)+'\\n';})()`);
  await importText('legacy-ui',legacy);await route('#/box/legacy-ui');await click('#tab-items');await click('#unlockBtn');await until(`!!document.querySelector('#new-record')`);
  ok(await run(`lib.get('legacy-ui').then(r=>r.sourceText)`)===legacy,'opening a legacy note does not migrate or rewrite its original source');
  await btn('Edit');await btn('Reveal');await fill('#record-title','Recovered note');await click('#save-record');await until(`!document.querySelector('#record-title')`);
  const migrated=await run(`(async()=>{const C=await import('./crypto.js'),W=await import('./webauthn.js'),S=await import('./store.js');const active=await lib.get('legacy-ui');const before=await S.backups.list('legacy-ui');return {version:active.box.v,note:JSON.parse(await C.decryptText(await W.unlockVault(active.box),active.box.items[0])).fields[0].value,backups:before.map(b=>b.sourceText)};})()`);
  ok(migrated.version===3&&migrated.note==='prefix\r\nSecret Key: 0001\rtrailing  '&&migrated.backups[0]===legacy,'approved migration preserves the entire untouched CR/CRLF note and exact encrypted backup');
  await click('#tab-sync');await btn('Delete from this browser');await btn('Yes, delete from this browser');await until(`location.hash==='#/'`);
  ok(await has('Retained backups')&&await has('legacy-ui')&&!await run(`lib.get('legacy-ui').then(Boolean)`),'deleted boxes retain globally discoverable downloadable migration backups');
  await importText('legacy-failure',legacy);await route('#/box/legacy-failure');await click('#tab-items');await click('#unlockBtn');await until(`!!document.querySelector('#new-record')`);
  await btn('Edit');await fill('#record-title','Draft survives failure');
  await run(`window.__realAdd=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(){throw new DOMException('synthetic quota','QuotaExceededError');};`);
  await click('#save-record');await until(`document.querySelector('#status').textContent.includes('Could not retain')`);
  await run(`IDBObjectStore.prototype.add=window.__realAdd;`);
  ok(await run(`document.querySelector('#record-title')?.value==='Draft survives failure'`)&&await run(`lib.get('legacy-failure').then(r=>r.sourceText)`)===legacy,'real backup storage failure preserves the active source and the live editor draft');
  await run(`window.__realPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='boxes')throw new DOMException('synthetic quota','QuotaExceededError');return window.__realPut.apply(this,args);};`);
  await click('#save-record');await until(`document.querySelector('#status').textContent.includes('Could not save')`);
  await run(`IDBObjectStore.prototype.put=window.__realPut;`);
  ok(await run(`document.querySelector('#record-title')?.value==='Draft survives failure'`)&&await run(`lib.get('legacy-failure').then(r=>r.sourceText)`)===legacy,'real active-write failure after backup preserves the source and draft');
  await click('#save-record');await until(`!document.querySelector('#record-title')`);
  const unsupported=await run(`(async()=>{const C=await import('./crypto.js'),W=await import('./webauthn.js');const box=(await lib.get('rich')).box,data=await W.unlockVault(box);return JSON.stringify({...box,items:[...box.items,await C.encryptText(data,JSON.stringify({format:'future',version:9}))]});})()`);
  await importText('unsupported',unsupported);await route('#/box/unsupported');await click('#tab-items');await click('#unlockBtn');await until(`document.body.innerText.includes('Read-only:')`);
  ok(await has('Replacement saved')&&await run(`document.querySelector('#new-record').disabled`),'supported siblings remain viewable while an unknown payload makes the whole box read-only');
  await btn('Edit');
  ok(!await run(`!!document.querySelector('#record-title')`)&&await run(`lib.get('unsupported').then(r=>r.sourceText)`)===unsupported,'unsupported sibling refuses editing without rewriting encrypted data');
  await click('#tab-sync');await click('#dlBtn');
  for(let attempt=0;attempt<30&&!fs.existsSync(path.join(profile,'unsupported.json'));attempt++)await sleep(100);
  ok(fs.readFileSync(path.join(profile,'unsupported.json'),'utf8')===unsupported,'unsupported original source remains downloadable without projection');
  // Leave the original naming/recovery scenarios in their expected route.
  await route('#/box/two');
};
